export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';

export const GET_ARTICLE_DETAILS_REQUEST = 'GET_ARTICLE_DETAILS_REQUEST';
export const GET_ARTICLE_DETAILS_SUCCESS = 'GET_ARTICLE_DETAILS_SUCCESS';
export const GET_ARTICLE_DETAILS_FAIL = 'GET_ARTICLE_DETAILS_FAIL';
export const GET_ARTICLE_DETAILS_RESET = 'GET_ARTICLE_DETAILS_RESET';
