export const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export const GET_IMAGES_CATEGORY_REQUEST = 'GET_IMAGES_CATEGORY_REQUEST';
export const GET_IMAGES_CATEGORY_SUCCESS = 'GET_IMAGES_CATEGORY_SUCCESS';
export const GET_IMAGES_CATEGORY_FAIL = 'GET_IMAGES_CATEGORY_FAIL';

export const GET_IMAGE_DETAILS_REQUEST = 'GET_IMAGE_DETAILS_REQUEST';
export const GET_IMAGE_DETAILS_SUCCESS = 'GET_IMAGE_DETAILS_SUCCESS';
export const GET_IMAGE_DETAILS_FAIL = 'GET_IMAGE_DETAILS_FAIL';
